package com.example.zeldacompendium.presentation.ui.commons.locations

enum class LocationHelper(val commonLocation: String, val coordinates: String) {
   WEST_NECLUDA("West Necluda", "z4,1296,1524"),
   EAST_NECLUDA("East Necluda", "z4,2680,2508"),
   HYRULE_FIELD("Hyrule Field", "z4,-460,580"),
   NECLUDA_SEA("Necluda Sea", "z4,4140,2844"),
   HYRULE_RIDGE("Hyrule Ridge", "z4,-2384,-408"),
   GERUDO_HIGHLANDS("Gerudo Highlands", "z4,-4088,844"),
   FARON_GRASSLANDS("Faron Grasslands", "z4,-424,3156"),
   LANAYRU_SEA("Lanayru Sea", "z4,4676,-196"),
   LANAYRU_GREAT_SPRING("Lanayru Great Spring", "z4,3696,260"),
   ELDIN_CANYON("Eldin Canyon", "z4,1852,-1400"),
   DEATH_MOUNTAIN("Death Mountain", "z4,2524,-2768"),
   GREAT_HYRULE_FOREST("Great Hyrule Forest", "z4,364,-2544"),
   ELDIN_MOUNTAINS("Eldin Mountains", "z4,1312,-3368"),
   GERUDO_DESERT("Gerudo Desert", "z4,-3664,3368"),
   TABANTHA_FRONTIER("Tabantha Frontier", "z4,-3476,-1180"),
   HEBRA_MOUNTAINS("Hebra Mountains", "z4,-3080,-3024"),
   GREATER_HYRULE("Greater Hyrule", "z2,-240,8"),
   AKKALA_HIGHLANDS("Akkala Highlands", "z4,3652,-2224"),
   RITO_STABLE("Rito Stable", "z4,-3256,-1756"),
   AKKALA_SEA("Akkala Sea", "z4,4812,-3364"),
   FLORIA_BRIDGE("Floria Bridge", "z5,1738,3468"),
   SATORI_MOUNTAIN("Satori Mountain", "z5,-2228,338"),
   LANAYRU_WETLANDS("Lanayru Wetlands", "z4,1748,-116"),
   DEEP_AKKALA("Deep Akkala", "z4,3604,-3188"),
   CRENEL_PEAK("Crenel Peak", "z5,1172,-320"),
   SERES_SCABLANDS("Seres Scablands", "z5,-2324,-450"),
   LAKE_HYLIA("Lake Hylia", "z4,-148,25200"),
   LAKE_FLORIA("Lake Floria", "z5,1738,3532"),
   DIVINE_BEAST_VAH_MEDOH("Divine Beast Vah Medoh", "z6,-3614,-1862"),
   HYRULE_CASTLE("Hyrule Castle", "z5,-254,-612"),
   DIVINE_BEAST_VAH_RUDANIA("Divine Beast Vah Rudania", "z6,2451.85,-2559.08"),
   YIGA_CLAN_HIDEOUT("Yiga Clan Hideout", "z4,-3592,1380"),
   DIVINE_BEAST_VAH_RUTA("Divine Beast Vah Ruta", "z5,3662,-176"),
   MOUNT_LANAYRU("Mount Lanayru", "z4,3896,1420"),
   DIVINE_BEAST_VAH_NABORIS("Divine Beast Vah Naboris", "z5,-2110,2616"),
   GERUDO_TOWN("Gerudo Town", "https://objmap.zeldamods.org/#/map/z4,-3836,2916"),
   FARON("Faron", "z4,944,3016"),
   KAKARIKO_VILLAGE("Kakariko Village", "z4,1808,984"),
   GREAT_ABANDONED_CENTRAL_MINE("Great Abandoned Central Mine", ""),
   LANAYRU_WETLAND_DEPTHS("Lanayru Wetland Depths", ""),
   THUNDERHEAD_ISLES("Thunderhead Isles", ""),
   GREAT_SKY_ISLAND("Great Sky Island", ""),
   NORTH_TABANTHA_SKY_ARCHIPELAGO("North Tabantha Sky Archipelago", ""),
   ZORA_RIVER("Zora River", ""),
   HYRULE_CAVES("Hyrule Caves", ""),
   HYRULE_SKY_ISLANDS("Hyrule Sky Islands", ""),
   TABANTHA_SKY_ARCHIPELAGO("Tabantha Sky Archipelago", ""),
   WEST_HEBRA_SKY_ARCHIPELAGO("West Hebra Sky Archipelago", ""),
   FARON_NECLUDA("Faron Necluda", ""),
   ZORAS_DOMAIN("Zora's Domain", ""),
   ELDIN_GREAT_SPRING("Eldin Great Spring", ""),
   FARON_SEA("Faron Sea", ""),
   EAST_GERUDO_SKY_ARCHIPELAGO("East Gerudo Sky Archipelago", ""),
   ELDIN_SKY_ARCHIPELAGO("Eldin Sky Archipelago", ""),
   SOUTH_LANAYRU_SKY_ARCHIPELAGO("South Lanayru Sky Archipelago", ""),
   GERUDO_CANYON("Gerudo Canyon", ""),
   LANAYRU("Lanayru", ""),
   HATENO_VILLAGE("Hateno Village", ""),
   LURELIN_VILLAGE("Lurelin Village", ""),
   CENTRAL_HYRULE_SKY("Central Hyrule Sky", ""),
   TABANTHA_TUNRA("Tabantha Tundra", ""),
   NORTH_NECLUDA_SKY_ARCHIPELAGO("North Necluda Sky Archipelago", ""),
   HEBRA_MOUNTAINS_DEPTHS("Hebra Mountains Depths", ""),
   TABANTHA_FRONTIER_DEPTHS("Tabantha Frontier Depths", ""),
   ELDIN_MOUNTAINS_DEPTHS("Eldin Mountains Depths", ""),
   FIRE_TEMPLE("Fire Temple", ""),
   GERUDO_DESERT_SKY("Gerudo Desert Sky", ""),
   NECLUDA_SEA_SKY("Necluda Sea Sky", ""),
   CENTRAL_HYRULE_DEPTHS("Central Hyrule Depths", ""),
   GERUDO_DESERT_DEPTHS("Gerudo Desert Depths", ""),
   EAST_NECLUDA_DEPTHS("East Necluda Depths", ""),
   NORTH_AKKALA_SKY_ARCHIPELAGO("North Akkala Sky Archipelago", ""),
   RISING_ISLAND_CHAIN("Rising Island Chain", ""),
   SPIRIT_TEMPLE("Spirit Temple", ""),
   GERUDO_HIGHLANDS_DEPTHS("Gerudo Highlands Depths", ""),
   FARON_GRASSLANDS_DEPTHS("Faron Grasslands Depths", ""),
   DEATH_MOUNTAIN_DEPTHS("Death Mountain Depths", ""),
   WIND_TEMPLE("Wind Temple", ""),
   WATER_TEMPLE("Water Temple", ""),
   THYPHLO_RUINS("Thyphlo Ruins", ""),
   ELDIN_CANYON_DEPTHS("Eldin Canyon Depths", ""),
   WEST_NECLUDA_DEPTHS("West Necluda Depths", ""),
   THE_DEPTHS("The Depths", ""),
   DEEP_AKKALA_DEPTHS("Deep Akkala Depths", ""),
   LANAYRU_SKY_ARCHIPELAGO("Lanayru Sky Archipelago", ""),
   MOUNT_LANAYRU_DEPTHS("Mount Lanayru Depths", ""),
   LIGHTNING_TEMPLE("Lightning Temple", ""),
   NORTH_GERUDO_SKY_ARCHIPELAGO("North Gerudo Sky Archipelago", ""),
   HYRULE_RIDGE_DEPTHS("Hyrule Ridge Depths", ""),
   AKKALA_HIGHLANDS_DEPTHS("Akkala Highlands Depths", ""),
   ABANDONED_KAKARIKO_MINE("Abandoned Kakariko Mine", ""),
   NECLUDA_SKY_ARCHIPELAGO("Necluda Sky Archipelago", ""),
   SOUTH_ELDIN_SKY_ARCHIPELAGO("South Eldin Sky Archipelago", ""),
   LANAYRU_GREAT_SPRING_SKY("Lanayru Great Spring Sky", ""),
   LANAYRU_WETLANDS_DEPTHS("Lanayru Wetlands Depths", ""),
   LOMEI_LABYRINTH_ISLAND("Lomei Labyrinth Island", ""),
   RITO_VILLAGE("Rito Village", ""),
   GORON_CITY("Goron City", ""),
   GREAT_PLATEAU("Great Plateau", ""),
   UPLAND_ZORANA("Upland Zorana", ""),
   EVENTIDE_ISLAND("Eventide Island", "");

   companion object {
      fun fromCommonLocation(commonLocation: String): String? {
         return entries.find { it.commonLocation == commonLocation }?.coordinates
      }
   }
}